version: "3"
name: "sound-scripter"

services:
    # Postgres database
    db:
        image: postgres:alpine
        container_name: db
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=db
        volumes:
            - ./data:/var/lib/postgresql/data

    # RabbitMQ message broker
    message-broker:
        image: rabbitmq:latest
        container_name: message-broker
        restart: always
        ports:
            - "5672:5672"
        depends_on:
            - db

    # Redis PubSub for realtime server side events notifications
    pub-sub:
        image: redis
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        depends_on:
            - db

    # Backend
    backend:
        build:
            context: ./
            dockerfile: Dockerfile.backend
        container_name: backend
        restart: always
        env_file:
            - ./.env
        environment:
            - CELERY_BROKER=pyamqp://message-broker
            - LOCAL_STORAGE_BASE_PATH=${PWD}/data
            - REDIS_HOST=pub-sub
            - POSTGRES_HOST=db
        ports:
            - "8000:8000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data:/backend/data
        depends_on:
            - db
            - message-broker
            - pub-sub
